# Generated by Django 5.2.10 on 2026-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cast', models.TextField(help_text='Comma-separated list of cast members')),
                ('poster_url', models.URLField(max_length=500)),
                ('backdrop_url', models.URLField(max_length=500)),
                ('trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('netflix_available', models.BooleanField(default=False)),
                ('disney_plus_available', models.BooleanField(default=False)),
                ('prime_video_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-release_date'],
            },
        ),
    ]
